### PR TITLE
added `packageName` arg, and added a few semicolons

### PR DESCRIPTION
**Pull request by dovidweisz**
This addresses issue #2

### CODE REVIEW

**Comment by junosuarez** [comment]
thanks for the PR! I know travis isn't set up on this repo yet, but please add tests and remove the semicolons, and I'd be willing to merge this.

**Comment by dovidweisz** [comment]
@jsdnxx Why remove the semicolons?

**Comment by junosuarez** [comment]
please conform to the existing code style for the package- it's common courtesy

**Comment by junosuarez** [comment]
closed in favor of #5

**Pull request closed without merging**
